### ISSUE TITLE
Filter options for library types "Oxford Nanopore: ligation" and "Oxford Nanopore: rapid" not working

### ISSUE THREAD

**Issue by carolyncaron** [UofS-Pulse-Binfo/lims_rawseq#10]
In the Raw Sequence Search, I receive no results for using either filter for "Oxford Nanopore: ligation" or "Oxford Nanopore: rapid". There is currently data with these library types which should result from the search, which you can see by specifying "Oxford Nanopore" for Technology.

**Comment by Jiu9Shen** [comment]
The problem has configured: results won't able to display only when more than one filter options (e.g.: both "Oxford Nanopore: ligation" and "Oxford Nanopore: rapid") are selected. The situation applies to other search criteria (Index Type, Technology and Read Type) too.

**Comment by Jiu9Shen** [comment]
Follow Lacey's suggestion, the function of choosing multiple filter options is temporarily disabled by **editing View** so the bug of "no filter results" won't happen for now.

**Comment by laceysanderson** [comment]
This change was made on portal so we can close this issue.
